# Generated by Django 5.2.3 on 2025-06-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название раздела')),
                ('html_table', models.TextField(verbose_name='HTML таблица')),
                ('graph_image', models.ImageField(blank=True, null=True, upload_to='graphs/', verbose_name='График (PNG)')),
            ],
            options={
                'verbose_name': 'Статистика востребованности',
                'verbose_name_plural': 'Статистика востребованности',
            },
        ),
        migrations.CreateModel(
            name='GeneralStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название раздела')),
                ('html_table', models.TextField(verbose_name='HTML таблица')),
                ('graph_image', models.ImageField(blank=True, null=True, upload_to='graphs/', verbose_name='График (PNG)')),
            ],
            options={
                'verbose_name': 'Раздел статистики',
                'verbose_name_plural': 'Разделы статистики',
            },
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название раздела')),
                ('html_table', models.TextField(verbose_name='HTML таблица')),
                ('graph_image', models.ImageField(blank=True, null=True, upload_to='graphs/', verbose_name='График (PNG)')),
            ],
            options={
                'verbose_name': 'География',
                'verbose_name_plural': 'География',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название раздела')),
                ('html_table', models.TextField(verbose_name='HTML таблица')),
                ('graph_image', models.ImageField(blank=True, null=True, upload_to='graphs/', verbose_name='График (PNG)')),
            ],
            options={
                'verbose_name': 'Навыки',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание вакансии')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Навыки')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('salary', models.CharField(blank=True, max_length=100, null=True, verbose_name='Оклад')),
                ('region', models.CharField(max_length=255, verbose_name='Регион')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-published_at'],
            },
        ),
    ]
